### ISSUE TITLE
Some invisible characters are not removed

### ISSUE THREAD

**Issue by tormit** [voku/portable-utf8#101]
#### What is this feature about (expected vs actual behaviour)?

Some invisible characters like U+200E are not removed.
See https://www.fileformat.info/info/unicode/char/200e/index.htm.

There could be more.

#### How can I reproduce it?

1. Go to https://emptycharacter.com/
2. Method 1 - Copy with a button -> Copy to clipboard
3. `\voku\helper\UTF8::remove_invisible_characters('--PASTE IT HERE--')`
4. Expecting empty string, but it returns the input

#### Does it take minutes, hours or days to fix?

Not sure.

#### Any additional information?

**Comment by rowhel95** [comment]
I think [\x00-\x08\x0B\x0C\x0E-\x1F\x7F]
should be (?>[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]|\xC2[\x80-\xA0\xAD]|\xE2\x80[\x80-\x8F\xA8-\xAF]|\xE2\x81[\x9F-\xAF])

**Comment by voku** [comment]
@tormit @rowhel95 What do you think of this solution: https://github.com/voku/portable-ascii/commit/4c0e18a4d62cd2014a7e1f1fd428e8e00803f9fb#diff-4bd19c38191461e60b7528c89918cc8b92609b61a35dd2abdab01a970133af24R712

By default, I would keep the control characters because otherwise some texts could break and it would be a BC, what do you think?

**Comment by voku** [comment]
The new options are available in v5.4.50.

Happy Coding!

**Comment by tormit** [comment]
Thanks! Options solution is good.
