### ISSUE TITLE
fix_utf8 method on string in Russian returns "???????"

### ISSUE THREAD

**Issue by Lovecircle** [voku/portable-utf8#62]
#### What is this feature about (expected vs actual behaviour)?
fix_utf8 method on string in Russian returns "???????"

#### How can I reproduce it?
echo UTF8::fix_utf8("строка на русском");

**Comment by voku** [comment]
Thanks for the bug-report. I have fixed the bug in "UTF8::utf8_decode()" in version 3.1.29

**-> The problem**

I tried to adapt the naming of the methods from the php-core, so e.g. we can use "UTF8::strpos($haystack, $needle, $offset = 0)" for "strpos($haystack, $needle, $offset = 0)"

But sometimes this was not the best idea... so the name of "utf8_decode()" is really bad, because it is more like a "utf8_to_iso_8859_1()" function, but so in the code it looks like it can handle utf8-strings. :/

**-> The solution**

Now we will check if  "UTF8::utf8_decode()" fixed iso-encoding problems and otherwise we will keep the utf8-string. (but only if the second parameter is "true")
